# Generated by Django 2.2.7 on 2020-10-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioProjects',
            new_name='PortfolioProject',
        ),
    ]
