# Generated by Django 2.2.7 on 2020-10-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_auto_20201003_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('testimonial', models.TextField()),
                ('career', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Testimonial_image')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.AlterModelOptions(
            name='portfolioproject',
            options={'verbose_name': 'Portfolio Project', 'verbose_name_plural': 'Portfolio Projects'},
        ),
    ]
